openapi: 3.0.3
info:
  title: Collector Site
  version: 1.0.0
servers:
  - url: http://localhost:8080/CollectorSite
paths:
  #1
  '/rest/auth/login':
    post:
      operationId: doLogin
      tags:
        - autenticazione
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: successful login
          content:
            text/plain:
              schema:
                type: string
          headers:
            Authorization:
              schema:
                type: string
                pattern: 'Bearer [a-z0-9A-Z-]+'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  '/rest/auth/logout':
    delete:
      operationId: doLogout
      tags:
        - autenticazione
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: successful logout
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  #2
  '/rest/collezioni/{username}':
    get:
      operationId: getCollezioniPrivateUtente
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista collezioni private utente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collezione'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  #3
  '/rest/collezioni/{username}/condivise':
    get:
      operationId: getCollezioniCondiviseUtente
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Collezioni condivise con un utente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collezione'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  #4
  '/rest/collezioni/{id_collezione}':
    get:
      operationId: getCollezione
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id_collezione
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Collezione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collezione'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  '/rest/collezioni/{id_collezione}/dischi':
    get:
      operationId: getDischiCollezione
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id_collezione
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista dischi in una collezione
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Disco'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  #5
  '/rest/collezioni/{id_collezione}/dischi/{id_disco}':
    get:
      operationId: getDiscoCollezione
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id_collezione
          in: path
          required: true
          schema:
            type: string
        - name: id_disco
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Disco in una collezione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disco'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  #10
    put:
      operationId: updateDiscoCollezione
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id_collezione
          in: path
          required: true
          schema:
            type: string
        - name: id_disco
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Disco'
      responses:
        '204':
          description: no content
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  #6
  '/rest/collezioni/{id_collezione}/dischi/':
    post:
      operationId: addDiscoCollezione
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id_collezione
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Disco'
      responses:
        '200':
          description: Aggiungi disco alla collezione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disco'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  #7
  '/rest/collezioni/{username}/dischi':
    get:
        operationId: getDischiUtente
        tags:
            - collezioni
        security:
            - bearerAuth: [ ]
        parameters:
            - name: username
              in: path
              required: true
              schema:
                  type: string
            - name: anno
              in: query
              required: false
              schema:
                  type: integer
            - name: genere
              in: query
              required: false
              schema:
                  $ref: '#/components/schemas/Genere'
            - name: autore
              in: query
              required: false
              schema:
                  type: string
            - name: titolo
              in: query
              required: false
              schema:
                  type: string
            - name: etichetta
              in: query
              required: false
              schema:
                  type: string
        responses:
            '200':
              description: Lista dischi di un utente filtrati
              content:
                application/json:
                  schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/Disco'
            '401':
              $ref: '#/components/responses/UnauthorizedError'
            '500':
              $ref: '#/components/responses/GeneralError'
            '404':
              $ref: '#/components/responses/NotFoundError'
  '/rest/collezioni/dischi':
    get:
      operationId: getDischiPubblici
      tags:
        - collezioni
      parameters:
        - name: anno
          in: query
          required: false
          schema:
            type: integer
        - name: genere
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Genere'
        - name: autore
          in: query
          required: false
          schema:
            type: string
        - name: titolo
          in: query
          required: false
          schema:
            type: string
        - name: etichetta
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista dischi filtrati
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Disco'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  '/rest/collezioni/{username}/condivise/dischi':
    get:
      operationId: getDischiCondivisiUtente
      tags:
        - collezioni
      security:
        - bearerAuth: [ ]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: anno
          in: query
          required: false
          schema:
            type: integer
        - name: genere
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Genere'
        - name: autore
          in: query
          required: false
          schema:
            type: string
        - name: titolo
          in: query
          required: false
          schema:
            type: string
        - name: etichetta
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista dischi condivisi con un utente filtrati
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Disco'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  #8
  '/rest/autori':
    get:
      operationId: getAutori
      parameters:
        - $ref: '#/components/parameters/pagerFrom'
        - $ref: '#/components/parameters/pagerTo'
      responses:
        '200':
          description: Lista di tutti gli autori
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Autore'
        '500':
          $ref: '#/components/responses/GeneralError'
  #9
  '/rest/autori/{id}':
    get:
      operationId: getAutore
      parameters:
        - name: id_autore
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Autore
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Autore'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/GeneralError'
  '/rest/autori/{id}/dischi':
    get:
      operationId: getDischiByAutore
      parameters:
        - name: id_autore
          in: query
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/pagerFrom'
        - $ref: '#/components/parameters/pagerTo'
      responses:
        '200':
          description: Lista di tutti i dischi di un autore
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dischi'
        '500':
          $ref: '#/components/responses/GeneralError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: internalToken
  responses:
    GeneralError:
      description: errore generale
      content:
        text/plain:
          schema:
            type: string
            example: "Messaggio di Errore"
    UnauthorizedError:
      description: bearer token mancante o non valido
    NotFound:
      description: elemento non trovato
      content:
        text/plain:
          schema:
            type: string
            example: "Elemento inesistente"
    BadRequest:
        description: richiesta non valida
        content:
            text/plain:
              schema:
                type: string
                example: "Richiesta non valida"
    Forbidden:
        description: operazione non permessa
        content:
            text/plain:
              schema:
                type: string
                example: "Operazione non permessa"
  parameters:
    pagerFrom:
      name: from
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
    pagerTo:
      name: to
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
  schemas:
    Utente:
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        username:
          type: string
          example: "username"
        password:
          type: string
          example: "password"
        email:
            type: string
            format: email
            example: "email@email.com"
        nome:
          type: string
          example: "Mario"
        cognome:
            type: string
            example: "Rossi"
        collezioni:
          type: array
          items:
              $ref: '#/components/schemas/Collezione'
    Collezione:
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        titolo:
          type: string
          example: "Titolo Collezione"
        privacy:
          type: string
          example: "privato"
        dataCreazione:
          type: string
          format: date
          readOnly: true
        utente:
          $ref: '#/components/schemas/Utente'
        dischi:
          type: array
          items:
              $ref: '#/components/schemas/Disco'
        condivisione:
          type: array
          items:
              $ref: '#/components/schemas/Utente'
    Disco:
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        titolo:
          type: string
          example: "Titolo Disco"
        anno:
          type: integer
          example: 2022
        genere:
          $ref: '#/components/schemas/Genere'
        etichetta:
          type: string
          example: "Etichetta"
        barcode:
          type: string
          example: "978020137962"
        utente:
          $ref: '#/components/schemas/Utente'
        autore:
          type: array
          items:
            $ref: '#/components/schemas/Autore'
        immagini:
          type: array
          items:
            $ref: '#/components/schemas/Immagine'
        tracce:
          type: array
          items:
            $ref: '#/components/schemas/Traccia'
        stato_conservazione:
          $ref: '#/components/schemas/StatoConservazione'
        formato:
          $ref: '#/components/schemas/Formato'
        dataCreazione:
          type: string
          format: date
          readOnly: true
        padre:
          $ref: '#/components/schemas/Disco'
    Autore:
        type: object
        properties:
          id:
            type: integer
            format: int32
            readOnly: true
          nome:
            type: string
            example: "Albano"
          cognome:
            type: string
            example: "Carrisi"
          nome_artistico:
            type: string
            example: "Al Bano"
          tipologia:
            $ref: '#/components/schemas/Tipologia'
          dischi:
            type: array
            items:
              $ref: '#/components/schemas/Disco'
    Immagine:
        type: object
        properties:
          id:
            type: integer
            format: int32
            readOnly: true
          filename:
            type: string
          disco:
            $ref: '#/components/schemas/Disco'
    Traccia:
        type: object
        properties:
          id:
            type: integer
            format: int32
            readOnly: true
          titolo:
            type: string
            example: "Titolo Traccia"
          durata:
            type: integer
            example: 120
          iswc:
            type: string
            minLength: 15
            maxLength: 15
            example: "T-034.524.680-C"
          dataCreazione:
            type: string
            format: date
            readOnly: true
          dischi:
            type: array
            items:
              $ref: '#/components/schemas/Disco'
          autori:
            type: array
            items:
              $ref: '#/components/schemas/Autore'
          padre:
            $ref: '#/components/schemas/Traccia'
    Genere:
      type: string
      enum:
        - ROCK
        - METAL
        - POP
        - JAZZ
        - CLASSICA
        - MELODICA
        - RAP
    StatoConservazione:
      type: string
      enum:
        - NUOVO
        - BUONO
        - MEDIO
        - ROVINATO
    Tipologia:
      type: string
      enum:
        - COMPOSITORE
        - CANTANTE
        - MUSICISTA
    Formato:
      type: string
      enum:
        - CD
        - VINYL
        - DIGITAL




